swagger: '2.0'
info:
  title: Vigenere Cipher Encryption/Decryption API
  version: "1.0"

paths:
  /api/encrypt:
    post:
      summary: Encrypt text with a given key
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: payload
          required: true
          schema:
            type: object
            properties:
              plain_text:
                type: string
                description: The text to be encrypted.
              key:
                type: string
                description: The encryption key (minimum length of 7).
      responses:
        200:
          description: Text encrypted successfully
          schema:
            type: object
            properties:
              message:
                type: string
              encrypted_text:
                type: string
        400:
          description: Invalid input

  /api/decrypt:
    post:
      summary: Decrypt text with a given key
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: payload
          required: true
          schema:
            type: object
            properties:
              cipher_text:
                type: string
                description: The text to be decrypted.
              key:
                type: string
                description: The decryption key (minimum length of 7).
      responses:
        200:
          description: Text decrypted successfully
          schema:
            type: object
            properties:
              message:
                type: string
              decrypted_text:
                type: string
        400:
          description: Invalid input
