PERMITTED_CHARACTERS = 'AĂÎBCDEFGHIÎJKLMNOPQRSȘTȚUVWXYZ'
PERMITTED_CHARACTERS += PERMITTED_CHARACTERS.lower()
PERMITTED_CHARACTERS = "0-9" + PERMITTED_CHARACTERS
REGEX_PATTERN_SUBSTITUTION = f"[^{PERMITTED_CHARACTERS}]"
REGEX_PATTERN_VALIDATION = f"^[{PERMITTED_CHARACTERS} ]+$"
