ALPHABET = "AĂÎBCDEFGHIÎJKLMNOPQRSȘTȚUVWXYZ"
ALPHABET_DIGITS = "0123456789" + ALPHABET

PERMITTED_CHARACTERS = ALPHABET
PERMITTED_CHARACTERS += PERMITTED_CHARACTERS.lower()
PERMITTED_CHARACTERS = "0-9" + PERMITTED_CHARACTERS

# Adjustment - maintain space in the message
# REGEX_PATTERN_SUBSTITUTION = f"[^{PERMITTED_CHARACTERS} ]"
REGEX_PATTERN_SUBSTITUTION = f"[^{PERMITTED_CHARACTERS}]"
REGEX_PATTERN_VALIDATION = f"^[{PERMITTED_CHARACTERS} ]+$"

LENGTH_KEY = 7
